apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: myregistry/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: KEYCLOAK_SERVER_URL
          value: "http://keycloak:8080/auth"
        - name: KEYCLOAK_CLIENT_ID
          value: "myclient"
        - name: KEYCLOAK_REALM
          value: "myrealm"
        - name: KEYCLOAK_CLIENT_SECRET
          value: "mysecret"